### ISSUE TITLE
Qual a cor do Céu

### ISSUE THREAD

**Issue by dherkyan** [joaovaledosantos/java-challenge-playground#5]
O sistema deve exibir a pergunta **Qual a cor de céu?**
Caso o usuário informe como resposta a cor **azul** o sistema deve apresentar a mensagem: **Parabéns\O/ Você acertou!**
Caso informe algo diferente de azul o sistema deve apresentar a mensagem: **Você errou! :(**

**Comment by joaovaledosantos** [comment]
Desafio concluído
