### ISSUE TITLE
O Brasil já venceu quantas Copas do Mundo

### ISSUE THREAD

**Issue by dherkyan** [joaovaledosantos/java-challenge-playground#6]
O sistema de exibir a pergunta: **O Brasil já venceu quantas Copas do Mundo?**
Caso o usuário informe **5** o sistema de exibir a mensagem: **Parabéns você  acertou\O/**
Caso informe um número diferente de 5 o sistema de exibir a mensagem: **Você errou :(**

**Comment by joaovaledosantos** [comment]
Desafio concluído
