### ISSUE TITLE
Qual a cor da camisa da seleção brasileira

### ISSUE THREAD

**Issue by dherkyan** [joaovaledosantos/java-challenge-playground#7]
O sistema de exibir a pergunta: **Qual a cor da camisa da seleção brasileira?**
Caso o usuário informe umas das cores azul ou amarela o sistema de exibir a mensagem: **Parabéns você acertou\O/**
Caso informe uma cor diferente o sistema de exibir a mensagem: **Você errou :(**

**Comment by joaovaledosantos** [comment]
Desafio concluído
